import psutil

# CPU
print(psutil.cpu_times(percpu=False))
print(psutil.cpu_times())
print(psutil.cpu_times_percent(interval=None, percpu=False))
print(psutil.cpu_count(logical=True))
# print(len(psutil.Process().cpu_affinity()))
print(psutil.cpu_stats())
print(psutil.cpu_freq(percpu=False))
print(psutil.getloadavg())

# MEMORY
print(psutil.virtual_memory())
print(psutil.swap_memory())

# DISK
print(psutil.disk_partitions(all=False))
print(psutil.disk_usage("/System/Volumes/Data"))
print(psutil.disk_io_counters(perdisk=False, nowrap=True))
#FUNCTIONS
print(psutil.pids())
print(psutil.process_iter(attrs=None, ad_value=None))
#print(psutil.pid_exists(pid))
#print(psutil.wait_procs(procs, timeout=None, callback=None))
#EXCEPTIONS
#print(class psutil.Error)
#print(class psutil.NoSuchProcess(pid, name=None, msg=None))
#print(class psutil.ZombieProcess(pid, name=None, ppid=None, msg=None))
#print(class psutil.AccessDenied(pid=None, name=None, msg=None))
#print(classpsutil.TimeoutExpired(seconds, pid=None, name=None, msg=None))
#OPERATING SYSTEM CONSTANTS
print(psutil.POSIX)
print(psutil.LINUX)
print(psutil.WINDOWS)
print(psutil.MACOS)
print(psutil.FREEBSD)
print(psutil.NETBSD)
print(psutil.OPENBSD)
print(psutil.BSD)
print(psutil.SUNOS)
print(psutil.AIX)
print(psutil.OSX)
print(psutil.PROCFS_PATH)
#PROCESS STATUS CONSTANTS
print(psutil.STATUS_RUNNING)
print(psutil.STATUS_SLEEPING)
print(psutil.STATUS_DISK_SLEEP)
print(psutil.STATUS_STOPPED)
print(psutil.STATUS_TRACING_STOP)
print(psutil.STATUS_ZOMBIE)
print(psutil.STATUS_DEAD)
print(psutil.STATUS_WAKE_KILL)
print(psutil.STATUS_WAKING)
#print(psutil.STATUS_PARKED(Linux))
#print(psutil.STATUS_IDLE(Linux, macOS, FreeBSD))
#print(psutil.STATUS_LOCKED(FreeBSD))
#print(psutil.STATUS_WAITING(FreeBSD))
#print(psutil.STATUS_SUSPENDED(NetBSD))
#PROCESS PRIORITY CONSTANTS
print(psutil.REALTIME_PRIORITY_CLASS)
print(psutil.HIGH_PRIORITY_CLASS)
print(psutil.ABOVE_NORMAL_PRIORITY_CLASS)
print(psutil.NORMAL_PRIORITY_CLASS)
print(psutil.IDLE_PRIORITY_CLASS)
print(psutil.BELOW_NORMAL_PRIORITY_CLASS)
print(psutil.IOPRIO_CLASS_NONE)
print(psutil.IOPRIO_CLASS_RT)
print(psutil.IOPRIO_CLASS_BE)
print(psutil.IOPRIO_CLASS_IDLE)
print(psutil.IOPRIO_VERYLOW)
print(psutil.IOPRIO_LOW)
print(psutil.IOPRIO_NORMAL)
print(psutil.IOPRIO_HIGH)
#PROCESS RESOURCES CONSTANTS
print(psutil.RLIM_INFINITY)
print(psutil.RLIMIT_AS)
print(psutil.RLIMIT_CORE)
print(psutil.RLIMIT_CPU)
print(psutil.RLIMIT_DATA)
print(psutil.RLIMIT_FSIZE)
print(psutil.RLIMIT_MEMLOCK)
print(psutil.RLIMIT_NOFILE)
print(psutil.RLIMIT_NPROC)
print(psutil.RLIMIT_RSS)
print(psutil.RLIMIT_STACK)
print(psutil.RLIMIT_LOCKS)
print(psutil.RLIMIT_MSGQUEUE)
print(psutil.RLIMIT_NICE)
print(psutil.RLIMIT_RTPRIO)
print(psutil.RLIMIT_RTTIME)
print(psutil.RLIMIT_SIGPENDING)
#CONNECTION CONSTANTS
print(psutil.CONN_ESTABLISHED)
print(psutil.CONN_SYN_SENT)
print(psutil.CONN_SYN_RECV)
print(psutil.CONN_FIN_WAIT1)
print(psutil.CONN_FIN_WAIT2)
print(psutil.CONN_TIME_WAIT)
print(psutil.CONN_CLOSE)
print(psutil.CONN_CLOSE_WAIT)
print(psutil.CONN_LAST_ACK)
print(psutil.CONN_LISTEN)
print(psutil.CONN_CLOSING)
print(psutil.CONN_NONE)
#HARDWARE CONSTANTS
print(psutil.AF_LINK)
print(psutil.NIC_DUPLEX_FULL)
print(psutil.NIC_DUPLEX_HALF)
print(psutil.NIC_DUPLEX_UNKNOWN)
print(psutil.POWER_TIME_UNKNOWN)
print(psutil.POWER_TIME_UNLIMITED)
print(psutil.version_info)
